"use client";
import {useMemo,useState} from "react";
import {ShoppingCart,MessageCircle,Instagram,Facebook,Flame,Star,Clock,MapPin,Plus,Minus,Trash2} from "lucide-react";
const WA="5519999999999";
const pizzas=[
["Margherita","Tradicionais","Molho de tomate, muçarela, tomate, manjericão e azeite.",49.9,"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85"],
["Calabresa Artesanal","Tradicionais","Muçarela, calabresa, cebola roxa e orégano.",52.9,"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1000&q=85"],
["Portuguesa da Casa","Tradicionais","Muçarela, presunto, ovos, cebola, azeitonas e ervas.",56.9,"https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1000&q=85"],
["Parma & Rúcula","Especiais","Muçarela, presunto cru, rúcula, parmesão e redução balsâmica.",69.9,"https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=1000&q=85"],
["Quattro Formaggi","Especiais","Muçarela, gorgonzola, parmesão e provolone.",67.9,"https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1000&q=85"],
["Funghi & Alho-Poró","Especiais","Muçarela, cogumelos, alho-poró, parmesão e ervas.",65.9,"https://images.unsplash.com/photo-1566843972142-a7fcb70de55a?auto=format&fit=crop&w=1000&q=85"],
["Chocolate & Morango","Doces","Chocolate cremoso, morangos e toque de açúcar.",54.9,"https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=1000&q=85"],
["Banana Caramelada","Doces","Banana, canela, açúcar mascavo e doce de leite.",51.9,"https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=1000&q=85"]
].map((p,i)=>({id:i,name:p[0],cat:p[1],desc:p[2],price:p[3],img:p[4]}));
const sizes={Média:0,Grande:12,Família:22}, crusts={Tradicional:0,Catupiry:8,Cheddar:8};
const money=n=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Home(){
 const[cat,setCat]=useState("Tradicionais"),[cart,setCart]=useState([]),[open,setOpen]=useState(null);
 const total=useMemo(()=>cart.reduce((s,i)=>s+i.unit*i.qty,0),[cart]);
 const add=(p,size,crust)=>{setCart(c=>[...c,{...p,key:Date.now()+Math.random(),size,crust,unit:p.price+sizes[size]+crusts[crust],qty:1}]);setOpen(null)};
 const order=()=>{if(!cart.length)return;const lines=cart.map(i=>`• ${i.qty}x ${i.name} — ${i.size}, borda ${i.crust} — ${money(i.unit*i.qty)}`);window.open(`https://wa.me/${WA}?text=${encodeURIComponent(`Olá, Bella Forneria! Gostaria de fazer este pedido:\n\n${lines.join("\n")}\n\nTotal: ${money(total)}\n\nNome:\nEndereço:\nForma de pagamento:`)}`,"_blank")};
 return <main><header><a className="brand" href="#inicio"><span><Flame/></span>Bella <b>Forneria</b></a><nav><a href="#cardapio">Cardápio</a><a href="#historia">Nossa história</a><a href="#contato">Contato</a></nav><a className="btn" href="#cardapio">Pedir agora</a></header>
 <section id="inicio" className="hero"><div className="shade"/><div className="heroText"><small>PIZZARIA ARTESANAL • MOGI GUAÇU</small><h1>Da massa ao forno,<br/><em>sabor que conquista.</em></h1><p>Tradição italiana, preparo artesanal e sabor de verdade.</p><a className="btn" href="#cardapio">Ver cardápio</a><div className="stats"><span><Star/>4,9 avaliação</span><span><Clock/>Entrega rápida</span><span><Flame/>Forno bem quente</span></div></div></section>
 <section className="dark"><div className="heading"><small>FEITO DIANTE DOS SEUS OLHOS</small><h2>O ritual da pizza perfeita</h2><p>Da massa aberta à mão aos ingredientes frescos e ao forno.</p></div><div className="video"><video autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1600&q=90"><source src="/pizza-loop.mp4" type="video/mp4"/></video><div className="videoCaption"><b>Bella Forneria</b><span>Da massa ao forno, sabor que conquista.</span></div></div></section>
 <section id="cardapio" className="section"><div className="heading"><small>NOSSO CARDÁPIO</small><h2>Escolha sua favorita</h2><p>Receitas clássicas, combinações especiais e um final doce.</p></div><div className="tabs">{["Tradicionais","Especiais","Doces"].map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="grid">{pizzas.filter(p=>p.cat===cat).map(p=><article key={p.id}><img src={p.img} alt={p.name}/><div><small>{p.cat}</small><h3>{p.name}</h3><p>{p.desc}</p><footer><b>{money(p.price)}</b><button onClick={()=>setOpen(p)}><Plus/></button></footer></div></article>)}</div></section>
 <section className="promo"><div><small>COMBO DA CASA</small><h2>Noite Bella</h2><p>2 pizzas grandes tradicionais + refrigerante 2L.</p><b>R$ 119,90</b></div><a className="btn light" href="#cardapio">Montar meu pedido</a></section>
 <section id="historia" className="story"><div className="storyImg"/><div><small>NOSSA HISTÓRIA</small><h2>Uma forneria feita para reunir pessoas.</h2><p>Massa preparada com tempo, ingredientes selecionados e aquele forno que transforma simplicidade em sabor.</p><p>Um ambiente visual que combina tradição italiana e rusticidade contemporânea.</p></div></section>
 <section className="reviews"><div className="heading"><small>QUEM PROVA, CONTA</small><h2>Momentos que viram tradição</h2></div><div className="reviewGrid">{[["Massa leve, borda perfeita e ingredientes muito bem equilibrados.","Marina A."],["Pedido simples pelo WhatsApp e pizza chegou com ótima apresentação.","Carlos R."],["A Parma & Rúcula virou a favorita aqui de casa.","Fernanda M."]].map(x=><blockquote key={x[1]}><b>★★★★★</b><p>“{x[0]}”</p><footer>{x[1]}</footer></blockquote>)}</div></section>
 <section id="contato" className="contact"><div><small>VENHA NOS VISITAR</small><h2>Bella Forneria</h2><p><MapPin/> Região central • Mogi Guaçu/SP</p><p><Clock/> Ter–Dom • 18h às 23h</p><i>Endereço e contatos demonstrativos.</i></div><div className="map"><MapPin/><b>Mogi Guaçu • SP</b><span>Localização ilustrativa</span></div></section>
 <footer className="siteFooter"><div className="brand"><span><Flame/></span>Bella <b>Forneria</b></div><p>Da massa ao forno, sabor que conquista.</p><div className="social"><Instagram/><Facebook/><b>𝕏</b></div><small>© 2026 Bella Forneria • Site demonstrativo</small></footer>
 <a className="wa" href={`https://wa.me/${WA}`} target="_blank"><MessageCircle/></a>
 {open&&<Config p={open} close={()=>setOpen(null)} add={add}/>} {cart.length>0&&<aside className="cart"><div className="cartTitle"><ShoppingCart/><b>Seu pedido</b></div>{cart.map(i=><div className="cartItem" key={i.key}><div><b>{i.name}</b><small>{i.size} • {i.crust}</small><strong>{money(i.unit*i.qty)}</strong></div><div className="controls"><button onClick={()=>setCart(c=>c.map(x=>x.key===i.key?{...x,qty:Math.max(1,x.qty-1)}:x))}><Minus/></button>{i.qty}<button onClick={()=>setCart(c=>c.map(x=>x.key===i.key?{...x,qty:x.qty+1}:x))}><Plus/></button><button onClick={()=>setCart(c=>c.filter(x=>x.key!==i.key))}><Trash2/></button></div></div>)}<div className="cartFoot"><b>Total: {money(total)}</b><button className="btn" onClick={order}><MessageCircle/> Enviar pelo WhatsApp</button></div></aside>}</main>}
function Config({p,close,add}){const[size,setSize]=useState("Média"),[crust,setCrust]=useState("Tradicional");return <div className="backdrop" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><h2>{p.name}</h2><p>{p.desc}</p><h4>Tamanho</h4><div className="choices">{Object.keys(sizes).map(x=><button className={size===x?"selected":""} onClick={()=>setSize(x)} key={x}>{x}<small>{sizes[x]?`+ ${money(sizes[x])}`:"Incluso"}</small></button>)}</div><h4>Borda</h4><div className="choices">{Object.keys(crusts).map(x=><button className={crust===x?"selected":""} onClick={()=>setCrust(x)} key={x}>{x}<small>{crusts[x]?`+ ${money(crusts[x])}`:"Inclusa"}</small></button>)}</div><button className="btn wide" onClick={()=>add(p,size,crust)}>Adicionar • {money(p.price+sizes[size]+crusts[crust])}</button></div></div>}
